name: sagae
description: SAGAE

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  data_connection_checker: ^0.3.4
  http: ^0.12.0+3
  simple_logger: ^1.7.0
  #state manager
  #  provider: ^4.0.2
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  #dependency injection
  get_it: ^3.1.0
  #NoSql database
  sembast: ^2.1.2+3
  path_provider: ^1.6.11
  #armazenar preferencias do app
  shared_preferences: ^0.5.8
  mask_text_input_formatter: ^1.0.7
  intl: ^0.16.1 #tipo string formater
  #equatable: ^1.2.4 #comparador de objetos tipo java
  geolocator: ^6.0.0
  #impede a tela de ser desligada por inatividade
  wakelock: ^0.1.4+2
  flutter_datetime_picker: ^1.4.0
  basic_utils: ^1.5.0
  image_picker: ^0.6.7+22
  wifi_info_flutter: 1.0.3
  imei_plugin: ^1.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  #code analysis and linting
  lint: ^1.1.1
  #flutter packages pub run build_runner build
  build_runner: ^1.10.0
  #auto generate fromJson and toJson
  #json_serializable: ^3.3.0
  mobx_codegen: ^1.1.0+1
  flutter_launcher_icons: ^0.7.5


#icons configuration
# flutter pub run flutter_launcher_icons:main - gera os icones
flutter_icons:
  android: true
  ios: true
  image_path: "dev_assets/images/bot.jpeg"
  adaptive_icon_background: "#191919"
  adaptive_icon_foreground: "dev_assets/images/bot.jpeg"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/home-brand.png
    - assets/images/bot.jpeg
    - assets/images/produtor-card.png
    - assets/images/tecnico-card.png
    - assets/images/atendimento_campo_card.png
    - assets/images/cadastrar_pessoa_card.png
    - assets/images/atendimento_virtual_card.png
    - assets/images/consultar_especialista_card.png
    - assets/images/evolucao_produtor_card.png
    - assets/images/cadeia_leite_card.png
    - assets/images/rodape_institucional.png
    - assets/images/sidebar_icon_agenda.png
    - assets/images/sidebar_icon_atendimento_campo.png
    - assets/images/sidebar_icon_atendimento_virtual.png
    - assets/images/sidebar_icon_cadastrar_indicador.png
    - assets/images/sidebar_icon_cadastrar_pessoa.png
    - assets/images/sidebar_icon_empaer.png
    - assets/images/sidebar_icon_evolucao_produtor.png
    - assets/images/sidebar_icon_falar_especialista.png
    - assets/images/sidebar_icon_noticias.png
    - assets/images/sidebar_icon_redes_sociais.png
    - assets/images/sidebar_icon_sair.png
    - assets/images/logo_dg.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
